### ISSUE TITLE
discovering thermostat timed out

### ISSUE THREAD

**Issue by faltim** [maxnowack/homebridge-eq3ble#13]
Hey, i installed the plugin but my thermostat isn't able to connect to my raspberry pi 2 model b with a bluetooth dongle.

To connect the Thermostat with `bluetoothctl` works fine. I can also use `gatttool -b 00:1a:22:0b:XX:XX --char-write-req --char-write-req --handle=0x0411 --value="4128E"` to set a value.

I tried already to reboot the pi, but it doesn't help.

This is my log in homebridge:

Connection closed
[2017-11-4 09:21:05] [Thermostat Wohnzimmer] cannot discover thermostat (00:1a:22:0b:XX:XX)
[2017-11-4 09:21:05] [Thermostat Wohnzimmer] Error: discovering thermostat timed out (00:1a:22:0b:XX:XX)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eq3ble/dist/thermostat.js:157:20)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
[2017-11-4 09:21:05] [Thermostat Wohnzimmer] connecting to thermostat (00:1a:22:0b:XX:XX)
[2017-11-4 09:21:05] [Thermostat Wohnzimmer] discovering thermostat (00:1a:22:0b:XX:XX)

Is there anybody who is able to give some help. That would be nice, thx :)

**Comment by faltim** [comment]
I fixed it by myself. I think it depended on permissions.
Im not sure, but I think this `sudo setcap cap_net_raw+eip $(eval readlink -f 'which node')` fixed the problem. I tried a lot, maybe something else did it.

**Comment by patafix18** [comment]
Hey,
do you have some other advices how to get rid of this error message?
I have the same problem but sudo setcap cap_net_raw+eip $(eval readlink -f 'which node') doesn't work for me.

**Comment by Hacki1111** [comment]
sudo setcap cap_net_raw+eip $(eval readlink -f 'which node')
is necessary to set permissions. Required packages are installed?

**Comment by patafix18** [comment]
Thanks a lot, now it works fine. It was an fault with the permissions.
Now I can change the temperature very quick. The problem is that the thermostat changes the date and time when changing the temperature. I guess it’s a problem with newer thermostat firmwares. 
I already read in some blogs about that but found no solution for this plugin.

**Comment by faltim** [comment]
@patafix18 What was your fault in detail? In my case it works now. But only when I start homebridge manually. After autostart it doesn't work at all. Does anyone have the same problem?
I autostart homebridge with the init.d script. I have a Raspberry Pi 2 Model B with an BLE dongle.

**Comment by patafix18** [comment]
I needed to install the plugin with sudo and unsafe permissions. After the installation I needed to start homebridge as root (sudo homebridge). I start homebridge with the init.d method too. You have to modify your init.d file and set the user from “pi” to “root”. Furthermore you should change your path to the correct /root/ path. 
Hope this will help you.
