### ISSUE TITLE
Time and date changes when changing the temperature. 

### ISSUE THREAD

**Issue by patafix18** [maxnowack/homebridge-eq3ble#15]
First of all thanks for the cool plugin.
I have an issue with the date of the thermostat. Everytime when I change the temperature the date of the thermostat changes too. It seems to be that this behaviour happens when getting the actual thermostate status.
Can you fix the problem?
I read in some forums about people have the same issue with the newer Firmware.

**Comment by jfc87** [comment]
same problem here, using newest firmware on CC-RT-BLE-EQ Thermostat

**Comment by patafix18** [comment]
Are you planning to fix this issue or is this project dead?

**Comment by joshhornby** [comment]
Did you ever get to the bottom of this @patafix18 @jfc87

**Comment by maxnowack** [comment]
The issue was fixed in maxnowack/node-eq3ble#6 a while ago. I'll upgrade the dependency and release a new version

**Comment by maxnowack** [comment]
Fixed in v1.3.3
