### ISSUE TITLE
How to install as an add-on in hassio?

### ISSUE THREAD

**Issue by JuanGrados** [maxnowack/homebridge-eq3ble#17]
Hi!

Thanks a lot for your plugin! It looks very nice but I do not find how I can install it in hassio using the add-on repository installation.

Is it even posible?

Thanks a lot!!

Cheers,
Juan

**Comment by maxnowack** [comment]
I don't know how to install homebridge plugins in home-assistant, but this looks promising: https://github.com/hassio-addons/addon-homebridge
