### ISSUE TITLE
How to I get the address of the thermostat on macOS

### ISSUE THREAD

**Issue by patricks** [maxnowack/homebridge-eq3ble#2]
Hi,

I have setup the homebridge plugin, but I don't know how to get the address of the thermostat? Is there any macOS/iOS tool to figure this out?

Btw. I have homebridge running on a macOS machine.

**Comment by aleksandrsivanovs** [comment]
on macOS you can open `System Preferences` -> `Bluetooth` and there you should see device with name `CC-RTE-BLE`.
Right click on the device will show you your device's MAC address:
<img width="675" alt="screenshot 2016-11-23 00 06 50" src="https://cloud.githubusercontent.com/assets/17889499/20544050/e17cedaa-b110-11e6-8b72-c2872f3667ec.png">

**Comment by patricks** [comment]
It look like its been removed with macOS Sierra. Also a alt-click doesn't show the address.

<img width="675" alt="screen shot 2016-11-23 at 06 12 08" src="https://cloud.githubusercontent.com/assets/132167/20551731/cd0b9e6a-b143-11e6-854f-a46b0114979a.png">

**Comment by aleksandrsivanovs** [comment]
can you try to pair to the device first (through the same menu)?

**Comment by patricks** [comment]
I was not able to connect to the thermostat, but I use a machine with El Captain, there I could figure out the address.

**Comment by maxnowack** [comment]
I couldn't find a comfortable way. But I'll write a small Node.js script for this.

**Comment by maxnowack** [comment]
Here's a simple script, to get the device information:
````js
/* usage:
npm install eq3ble
node thisfile.js */

var EQ3BLE = require('eq3ble').default;
EQ3BLE.discover(function (device) { console.log(device) });
````
