### ISSUE TITLE
adress mac

### ISSUE THREAD

**Issue by djrams10** [maxnowack/homebridge-eq3ble#21]
Hello, I can not find the mac address on the product. Could you help me? thank you

**Comment by djrams10** [comment]
this plugin is compatible with this model CC-RT-BLE-EQ?

**Comment by djrams10** [comment]
i have homebridge installed on a synology, do i have installed a bluetooth key on the synology so that it can communicate with?

**Comment by maxnowack** [comment]
How do you get the mac address of your device depends on your OS. Just google it ;)
Since this plugin uses bluetooth for the connection to the device, you need bluetooh on your synology

**Comment by djrams10** [comment]
this address "00: 1a: 22: 07: 48: 77" is the same for all the EQ3BLE thermostat? I will put the bluetooth on my synology, it should work? thanks

**Comment by maxnowack** [comment]
No, every device has a unique address. I'm not familar with synology, but I think it should work

**Comment by djrams10** [comment]
thank you with a device ios you know how I could get it or on mac? Thank you

**Comment by djrams10** [comment]
I sought the solution everywhere, I managed to find it.
