### ISSUE TITLE
Connecting to the thermostat takes very long

### ISSUE THREAD

**Issue by patricks** [maxnowack/homebridge-eq3ble#4]
I have used this plugin now for a few hours. But there is one "problem" it takes really long (> 5 seconds) to connect to the thermostat and send commands. I understand that this is a issue with BLE.

But the problem is that I have connected other devices (netatmo, philips hue) to the same bridge and if I just want to switch one light, I have to wait until the thermostat is connected. Btw. I only use HomeKit to control my lights, so this is a little bit annoying.

Is it possible to build something like a proxy, which responses really fast and communicates with the thermostat(s) (i am think about buying more 😉) in the background?

**Comment by patricks** [comment]
Here is what the homebridge developers responded. https://github.com/nfarina/homebridge/issues/948

So a proxy like system would be nice.

**Comment by maxnowack** [comment]
I faced the same issue on my setup. My workaround was to exclude the thermostats from the favorites.
Invoking the callback immediately and pushing the data if the thermostat is connected sounds like a solution for this issue. Sadly I couldn't find any information how I can do that.
@KhaosT do you know if there is an example for that?

Another solution could be to run the thermostat as a standalone server using [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS) directly (which is like running multiple homebridge instances, but with less overhead).
